import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Teslo shop - Login",
  description: "Generated by create next app",
};

export default function LoginPage() {
  return <div>LoginPage</div>;
}
